# Run the tests
# Todo : reuse a build from another action, instead of rebuilding for nothing.
# tchap modification : use "./scripts/layered.with.version.sh" instead of "./scripts/layered.sh"
name: Cypress End to End Tests
on:
  pull_request: { }
  push:
    branches: [ develop, master ]
  repository_dispatch: # :TCHAP: do we need this ?
    types: [ element-web-notify ]
env:
  # These must be set for fetchdep.sh to get the right branch
  REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 14

      - name: Install Dependencies
        run: "./scripts/layered.with.version.sh"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4.1.1
        with:
          # The built-in Electron runner seems to grind to a halt trying
          # to run the tests, so use chrome.
          browser: chrome
          install-command: '' # disable the default install, we used layered.with.version already.
          start: yarn start
          #start: npx serve -p 8080 webapp # If you have downloaded a build artifact, it will be in webapp dir.
          wait-on: 'http://localhost:8080'
          record: true
          command: 'yarn test:cypress'
        env:
          E2E_TEST_USER_EMAIL: 'e2e-test-user@tchap.beta.gouv.fr'
          E2E_TEST_USER_PASSWORD: 'todo get this from gihub secret'
          E2E_TEST_USER_SECURITY_KEY: 'todo get this from gihub secret'
          E2E_TEST_USER_HOMESERVER_URL: 'https://matrix.agent1.tchap.incubateur.net'
          E2E_TEST_USER_HOMESERVER_SHORT: 'agent1.tchap.incubateur.net'

