name: Node.js CI
on:
  push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16'
            cache: 'yarn'
      - run: ./scripts/fetch-develop.deps.sh --depth 1
      - run: yarn install
      - run: yarn build:genfiles
      - run: yarn test
